version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: jira_metrics
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - bridge_network

volumes:
  postgres:
    
networks:
  bridge_network:
    driver: bridge
